{{- /*
Create ServiceAccount if serviceAccount.create is true
*/ -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mem0-mcp-server.serviceAccountName" . }}
  labels:
    {{- include "mem0-mcp-server.labels" . | nindent 4 }}
{{- end }}